### ISSUE TITLE
[bug]: completely broken

### ISSUE THREAD

**Issue by zerebos** [ungiglio/DiscordDiscordia#30]
### What happened?

![image](https://github.com/user-attachments/assets/ab588384-ee26-4dcb-9757-7201bf5bed8e)

### Version

1.0.7 (Stable)

### What client are you seeing the problem on?

Desktop app

### What client mod are you seeing the problem on?

BetterDiscord

### Bug Priority

High

### Final Checklist

- [X] I have selected the appropriate priority level for this bug.
- [X] I have double-checked all the information in this report for accuracy.

**Comment by ungiglio** [comment]
Seems all good

**Comment by ungiglio** [comment]
outdated version, I'll upload the final one.
(btw its not broken, it's meant to be like that)
