### ISSUE TITLE
[F]: Font Change

### ISSUE THREAD

**Issue by HoneyAura** [ungiglio/DiscordDiscordia#32]
### Feature Description

The option to change font as a customization option in the .css file.

### Problem and Solution

The lack of ability to customize 100% of the theme.

### Potential Impact

Medium (Significant improvement)

### Contribution

I can provide more detailed specifications

### Final Checklist

- [X] I have reviewed my submission for clarity and completeness.

**Comment by ungiglio** [comment]
Fixed in [1.0.4](https://github.com/ungiglio/DiscordDiscordia/releases/tag/v1.0.4-awkglass)

pending approval from BetterDiscord...

**Comment by HoneyAura** [comment]
you're the best!

**Comment by ungiglio** [comment]
feel free to open another issue if something its not working as expected with fonts or more!
